pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx:2
    settings:
      platforms: linux/amd64
      repo: git.mylloon.fr/${CI_REPO,,}
      auto_tag: true
      registry: git.mylloon.fr
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      event: push
      branch: main
